version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "vote-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3fofl5ja9y6q"
s3_prefix = "vote-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

